version: 2.1

executors:
  py3:
    docker:
      - image: cimg/python:3.7
  circleci:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: xlarge

orbs:
  clair: ovotech/clair-scanner@1.6.0

jobs:
  build_debian_9:
    executor: py3
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace_cache
      - run:
          name: Build images
          command: make splunk-debian-9 uf-debian-9
      - run:
          name: Save images
          command: |
            docker save -o workspace_cache/splunk-debian-9.tar splunk-debian-9:latest
            docker save -o workspace_cache/uf-debian-9.tar uf-debian-9:latest
      - persist_to_workspace:
          root: workspace_cache
          paths:
            - splunk-debian-9.tar
            - uf-debian-9.tar

  build_debian_10:
    executor: py3
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace_cache
      - run:
          name: Build images
          command: make splunk-debian-10 uf-debian-10
      - run:
          name: Save images
          command: |
            docker save -o workspace_cache/splunk-debian-10.tar splunk-debian-10:latest
            docker save -o workspace_cache/uf-debian-10.tar uf-debian-10:latest
      - persist_to_workspace:
          root: workspace_cache
          paths:
            - splunk-debian-10.tar
            - uf-debian-10.tar

  build_redhat_8:
    executor: py3
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace_cache
      - run:
          name: Build images
          command: make splunk-redhat-8 uf-redhat-8
      - run:
          name: Save images
          command: |
            docker save -o workspace_cache/splunk-redhat-8.tar splunk-redhat-8:latest
            docker save -o workspace_cache/uf-redhat-8.tar uf-redhat-8:latest
      - persist_to_workspace:
          root: workspace_cache
          paths:
            - splunk-redhat-8.tar
            - uf-redhat-8.tar

  build_centos_7:
    executor: py3
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace_cache
      - run:
          name: Build images
          command: make splunk-centos-7 uf-centos-7
      - run:
          name: Save images
          command: |
            docker save -o workspace_cache/splunk-centos-7.tar splunk-centos-7:latest
            docker save -o workspace_cache/uf-centos-7.tar uf-centos-7:latest
      - persist_to_workspace:
          root: workspace_cache
          paths:
            - splunk-centos-7.tar
            - uf-centos-7.tar

  scan_images:
    executor: clair/default
    steps:
      - checkout
      - attach_workspace:
          at: workspace_cache
      - clair/scan:
          docker_tar_dir: /root/project/workspace_cache/

  debian10-testing:
    machine:
      image: circleci/classic:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Debian 10 Splunk
          command: |
            make splunk-debian-10
      - run:
          name: Build Debian 10 UF
          command: |
            make uf-debian-10
      - run:
          name: Test if image size increase
          command: make test_debian10_image_size
      - run:
          name: Run small Debian 10 image tests
          command: make run_small_tests_debian10
          no_output_timeout: 20m
      - run:
          name: Run large Debian 10 image tests
          command: make run_large_tests_debian10
          no_output_timeout: 1h
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  redhat8-testing:
    machine:
      image: circleci/classic:latest
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Redhat 8 Splunk
          command: |
            make splunk-redhat-8
      - run:
          name: Build Redhat 8 UF
          command: |
            make uf-redhat-8
      - run:
          name: Run small Redhat 8 image tests
          command: make run_small_tests_redhat8
          no_output_timeout: 20m
      - run:
          name: Run large Redhat 8 image tests
          command: make run_large_tests_redhat8
          no_output_timeout: 1h
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  container-validation:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Container
          command: |
            make all
      - run:
          name: Export Build Images for Artifacts
          command: |
            make save_containers
      - run:
          name: Test Python3 installation
          command: make test_python3_all
      - run:
          name: Test Python2 as the default
          command: make test_python2_all
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2
  pipeline:
    jobs:
      - build_debian_9
      - build_debian_10
      - build_centos_7
      - build_redhat_8
      - scan_images:
          requires:
            - build_debian_9
            - build_debian_10
            - build_centos_7
            - build_redhat_8
